# Partie 1
$words1 = @(
    "pomme", "terre", "deliege", "frite", "moules", "chocolat", "waffle", "fromage", "baguette",
    "croissant", "escargot", "vin", "tour", "eiffel", "louvre", "seine", "beret", "macaron",
    "crepe", "quiche", "ratatouille", "souffle", "baguette", "mousse", "fondue", "bistro",
    "brasserie", "cafe", "truffe", "paris", "bordeaux", "marseille", "nice", "lyon",
    "strasbourg", "grenoble", "nancy", "metz", "nantes", "toulouse", "bretagne", "normandie",
    "alsace", "provence", "chateau", "palais", "basilique", "console", "gamer", "controller", 
    "joystick", "keyboard", "mouse", "RPG", "FPS", "sandbox", "esport", "LAN", "MMORPG", 
    "PvP", "PvE", "stream", "VR", "AR", "gamerz", "speedrun", "tournament", "loot", "quest",
    "Wacraft", "Diablo", "Forza", "Fantasy", "Sony", "Microsoft", "Rewards", "Minecraft",
    "aventure", "bagage", "billet", "camp", "carte", "destination", "guide", "hotel", 
    "itineraire", "jungle", "marine", "mont", "navire", "oceane", "passport", "port", 
    "randonnee", "safari", "terminal", "train", "tribu", "valise", "voyage",
    "acteur", "scenariste", "realisateur", "producteur", "dialogue", "monologue", "script", "cast",
    "casting", "scene", "decors", "effets_speciaux", "sfx", "montage", "bande_annonce", "seance",
    "projection", "salle", "blockbuster", "independant", "festival", "palmare", "prix", "oscar",
    "cannes", "venise", "berlin", "toronto", "sundance", "premiere", "trailer", "clip", "court_metrage",
    "long_metrage", "vo", "vf", "avant_premiere", "camera", "objectif", "lumiere", "son", "prise_de_vue",
    "rush", "making_of", "featurette", "documentaire", "drame", "comedy", "horreur", "thriller", "suspense",
    "action", "aventure", "science_fiction", "fantastique", "animation", "animation_3D", "court",
    "long", "couleur", "noir_et_blanc", "film_culte", "classique", "critique", "cinema", "acteur_principal",
    "acteur_secondaire", "extra", "figurant", "script", "storyboard", "scenographie", "effets_visuels",
    "fx", "distribution", "diffusion", "rediffusion", "numero_un", "meilleur_acteur", "meilleur_film",
    "meilleure_actrice", "meilleur_second_role", "realisation", "production", "serie", "tv", "webserie",
    "video_a_la_demande", "streaming", "vfx", "cinematographie", "oeuvre", "rendu", "animation_numerique",
    "post_production"
)
# Partie 2
$words1 += @(
    "acidite", "albumine", "algorithme", "analyse", "anatomie", "angle", "animal",
    "antibiotique", "antidote", "antimatiere", "antioxydant", "aqua", "archaeologie", "arachnide",
    "astre", "astronaute", "astronomie", "atome", "bacterie", "balance", "biologie", "bionique",
    "biorobot", "biosphere", "bitume", "carbonique", "cellule", "cephalopode", "chimie", "chromatographie",
    "chromosome", "circuit", "climatologie", "clonage", "codon", "comete", "composant", "concentration",
    "conducteur", "constellation", "corps", "cristal", "cybernetique", "cyborg", "cycle", "cynogen",
    "decomposeur", "dendrite", "densite", "deplacement", "dernier_quart", "deshydratation", "determinisme",
    "detection", "detective", "diffraction", "digital", "dilatation", "dilution", "dinosaure", "diode",
    "dynamique", "electrolyte", "electromagnetisme", "electrophorese", "element", "energie", "enzyme",
    "equation", "erlenmeyer", "ethologie", "etat", "etat_souterrain", "event", "evolution", "exoplanete",
    "experimentation", "faune", "fermentation", "fiabilite", "fission", "flamme", "flora", "flux",
    "fosse", "fouissement", "fractionnement", "friction", "frottement", "fusion", "galaxie", "genetique",
    "genie", "geologie", "glacier", "gradient", "gravite", "halogene", "herbivore", "hormone", "hydro",
    "hydrocarbure", "hypothese", "immunite", "immunologie", "incandescence", "indice", "induction",
    "injection", "inoculum", "intelligence", "ionisation", "isotope", "jusant", "laser", "latitude",
    "leucocyte", "lumiere", "magnification", "masse", "mecanique", "medecine", "melanine", "menisque",
    "microbe", "microbe_urin", "microscope", "minerai", "mineral", "mitochondrie", "modulateur",
    "molecule", "mutation", "neutron", "neutrino", "neutrino_cosmique", "nucleon", "nutrition",
    "nucleotide", "nutritionnelle", "objectivite", "observation", "optoelectronique", "organisme",
    "organisation", "osmotique", "parametre", "pelerins", "phenomene", "photosynthese", "plasma",
    "pleine_lune", "polarisation", "pollution", "polynome", "polyvinyle", "potentiel", "proie",
    "protection", "protein", "protides", "proton", "pulsar", "quantique", "radioactive", "reaction",
    "rechauffement", "recherche", "revolution", "robotique", "sang", "savon", "sechage", "sediment",
    "semiconducteur", "sinus", "sismique", "solubilite", "solvant", "spectre", "spheroid",
    "sphericite", "stase", "stimulation", "subatomique", "substance", "superconducteur", "systeme",
    "systematique", "systeme_solaire", "technique", "telecommunication", "telescope", "tempete",
    "terrestre", "theoreme", "thermique", "thermodynamique", "thermometre", "tissu", "transformation",
    "transformation_phase", "transfuge", "transplantation", "traverser", "tresorerie", "ultraviolet",
    "univers", "vitesse", "volatil", "volume", "zoologie"
)
# Partie 3
$words1 += @(
    "cosmos", "galaxie", "asteroide", "comete", "constellation", "eclipse", "espace", "etoile",
    "nebuleuse", "orbite", "planete", "poussiere", "satellite", "trou_noir", "voie_lactee",
    "meteorite", "supernova", "quasar", "luminosite", "exploration", "interstellaire", "astrobiologie",
    "astrochimie", "astrophysique", "cosmologie", "gravitation", "heliosphere", "hyperespace",
    "megaparsec", "parsec", "perihelie", "periapside", "periastre", "photometrie", "redshift",
    "singularite", "solstice", "spectroscopie", "sphere_celeste", "superamas", "telescope", "troposphere",
    "zodiac", "accretion", "albedo", "anomalie", "apoastre", "apoapside", "aphelie", "apogee", "asterisme",
    "asteroseismologie", "aurora", "aurora_borealis", "azimut", "barycentre", "bolometrie", "cataclysme",
    "champ_magnetique", "chondrite", "corona", "croissant", "declinaison", "diagramme_Hertzsprung-Russell",
    "dichotomie", "equateur_celeste", "espace-temps", "excentricite", "exoplanete", "grand_attracteur",
    "habitable", "hypsometre", "inclinaison", "ionisation", "kelvin", "latitude", "longitude", "luminosite",
    "masse", "materiel", "mesure_parallaxe", "modulation_phase", "nadir", "object_messier", "opposition",
    "parallaxe", "planete_naine", "precession", "propulsion", "radiogalaxie", "rotation", "sinus",
    "solaire", "spectre", "stellite", "subsysteme", "syzygie", "tangente"
)
