# Partie 1
$words1 = @(
    "pomme", "terre", "deliege", "frite", "moules", "chocolat", "waffle", "fromage", "baguette",
    "croissant", "escargot", "vin", "tour", "eiffel", "louvre", "seine", "beret", "macaron",
    "crepe", "quiche", "ratatouille", "souffle", "baguette", "mousse", "fondue", "bistro",
    "brasserie", "cafe", "truffe", "paris", "bordeaux", "marseille", "nice", "lyon",
    "strasbourg", "grenoble", "nancy", "metz", "nantes", "toulouse", "bretagne", "normandie",
    "alsace", "provence", "chateau", "palais", "basilique", "console", "gamer", "controller", 
    "joystick", "keyboard", "mouse", "RPG", "FPS", "sandbox", "esport", "LAN", "MMORPG", 
    "PvP", "PvE", "stream", "VR", "AR", "gamerz", "speedrun", "tournament", "loot", "quest",
    "Wacraft", "Diablo", "Forza", "Fantasy", "Sony", "Microsoft", "Rewards", "Minecraft",
    "aventure", "bagage", "billet", "camp", "carte", "destination", "guide", "hotel", 
    "itineraire", "jungle", "marine", "mont", "navire", "oceane", "passport", "port", 
    "randonnee", "safari", "terminal", "train", "tribu", "valise", "voyage",
    "acteur", "scenariste", "realisateur", "producteur", "dialogue", "monologue", "script", "cast",
    "casting", "scene", "decors", "effets_speciaux", "sfx", "montage", "bande_annonce", "seance",
    "projection", "salle", "blockbuster", "independant", "festival", "palmare", "prix", "oscar",
    "cannes", "venise", "berlin", "toronto", "sundance", "premiere", "trailer", "clip", "court_metrage",
    "long_metrage", "vo", "vf", "avant_premiere", "camera", "objectif", "lumiere", "son", "prise_de_vue",
    "rush", "making_of", "featurette", "documentaire", "drame", "comedy", "horreur", "thriller", "suspense",
    "action", "aventure", "science_fiction", "fantastique", "animation", "animation_3D", "court",
    "long", "couleur", "noir_et_blanc", "film_culte", "classique", "critique", "cinema", "acteur_principal",
    "acteur_secondaire", "extra", "figurant", "script", "storyboard", "scenographie", "effets_visuels",
    "fx", "distribution", "diffusion", "rediffusion", "numero_un", "meilleur_acteur", "meilleur_film",
    "meilleure_actrice", "meilleur_second_role", "realisation", "production", "serie", "tv", "webserie",
    "video_a_la_demande", "streaming", "vfx", "cinematographie", "oeuvre", "rendu", "animation_numerique",
    "post_production"
)
# Partie 2
$words1 += @(
    "acidite", "albumine", "algorithme", "analyse", "anatomie", "angle", "animal",
    "antibiotique", "antidote", "antimatiere", "antioxydant", "aqua", "archaeologie", "arachnide",
    "astre", "astronaute", "astronomie", "atome", "bacterie", "balance", "biologie", "bionique",
    "biorobot", "biosphere", "bitume", "carbonique", "cellule", "cephalopode", "chimie", "chromatographie",
    "chromosome", "circuit", "climatologie", "clonage", "codon", "comete", "composant", "concentration",
    "conducteur", "constellation", "corps", "cristal", "cybernetique", "cyborg", "cycle", "cynogen",
    "decomposeur", "dendrite", "densite", "deplacement", "dernier_quart", "deshydratation", "determinisme",
    "detection", "detective", "diffraction", "digital", "dilatation", "dilution", "dinosaure", "diode",
    "dynamique", "electrolyte", "electromagnetisme", "electrophorese", "element", "energie", "enzyme",
    "equation", "erlenmeyer", "ethologie", "etat", "etat_souterrain", "event", "evolution", "exoplanete",
    "experimentation", "faune", "fermentation", "fiabilite", "fission", "flamme", "flora", "flux",
    "fosse", "fouissement", "fractionnement", "friction", "frottement", "fusion", "galaxie", "genetique",
    "genie", "geologie", "glacier", "gradient", "gravite", "halogene", "herbivore", "hormone", "hydro",
    "hydrocarbure", "hypothese", "immunite", "immunologie", "incandescence", "indice", "induction",
    "injection", "inoculum", "intelligence", "ionisation", "isotope", "jusant", "laser", "latitude",
    "leucocyte", "lumiere", "magnification", "masse", "mecanique", "medecine", "melanine", "menisque",
    "microbe", "microbe_urin", "microscope", "minerai", "mineral", "mitochondrie", "modulateur",
    "molecule", "mutation", "neutron", "neutrino", "neutrino_cosmique", "nucleon", "nutrition",
    "nucleotide", "nutritionnelle", "objectivite", "observation", "optoelectronique", "organisme",
    "organisation", "osmotique", "parametre", "pelerins", "phenomene", "photosynthese", "plasma",
    "pleine_lune", "polarisation", "pollution", "polynome", "polyvinyle", "potentiel", "proie",
    "protection", "protein", "protides", "proton", "pulsar", "quantique", "radioactive", "reaction",
    "rechauffement", "recherche", "revolution", "robotique", "sang", "savon", "sechage", "sediment",
    "semiconducteur", "sinus", "sismique", "solubilite", "solvant", "spectre", "spheroid",
    "sphericite", "stase", "stimulation", "subatomique", "substance", "superconducteur", "systeme",
    "systematique", "systeme_solaire", "technique", "telecommunication", "telescope", "tempete",
    "terrestre", "theoreme", "thermique", "thermodynamique", "thermometre", "tissu", "transformation",
    "transformation_phase", "transfuge", "transplantation", "traverser", "tresorerie", "ultraviolet",
    "univers", "vitesse", "volatil", "volume", "zoologie"
)
# Partie 3
$words1 += @(
    "cosmos", "galaxie", "asteroide", "comete", "constellation", "eclipse", "espace", "etoile",
    "nebuleuse", "orbite", "planete", "poussiere", "satellite", "trou_noir", "voie_lactee",
    "meteorite", "supernova", "quasar", "luminosite", "exploration", "interstellaire", "astrobiologie",
    "astrochimie", "astrophysique", "cosmologie", "gravitation", "heliosphere", "hyperespace",
    "megaparsec", "parsec", "perihelie", "periapside", "periastre", "photometrie", "redshift",
    "singularite", "solstice", "spectroscopie", "sphere_celeste", "superamas", "telescope", "troposphere",
    "zodiac", "accretion", "albedo", "anomalie", "apoastre", "apoapside", "aphelie", "apogee", "asterisme",
    "asteroseismologie", "aurora", "aurora_borealis", "azimut", "barycentre", "bolometrie", "cataclysme",
    "champ_magnetique", "chondrite", "corona", "croissant", "declinaison", "diagramme_Hertzsprung-Russell",
    "dichotomie", "equateur_celeste", "espace-temps", "excentricite", "exoplanete", "grand_attracteur",
    "habitable", "hypsometre", "inclinaison", "ionisation", "kelvin", "latitude", "longitude", "luminosite",
    "masse", "materiel", "mesure_parallaxe", "modulation_phase", "nadir", "object_messier", "opposition",
    "parallaxe", "planete_naine", "precession", "propulsion", "radiogalaxie", "rotation", "sinus",
    "solaire", "spectre", "stellite", "subsysteme", "syzygie", "tangente"
)
# Partie 4
$words1 += @(
    "auteur", "biographie", "chapitre", "citations", "classement", "comics", "collection",
    "couverture", "critique", "dictionnaire", "dos", "edition", "ecrivain", "encre", 
    "essai", "fiction", "genre", "grammaire", "impression", "index", "litterature", "livre",
    "manuscrit", "marque-page", "nouvelle", "ouvrage", "page", "plume", "poesie", "prologue",
    "publication", "reliure", "resume", "roman", "saga", "scenariste", "sous-titre", "synopsis",
    "table", "tableau", "texte", "typographie", "volume", "bibliographie", "conception",
    "conteur", "conte", "couverture", "edition", "editeur", "epilogue", "illustrateur", "imprimeur",
    "introduction", "isbn", "librairie", "lecteur", "legende", "memoire", "memoires", "narration",
    "narrateur", "oeuvre", "ouvrage", "paragraphe", "poche", "poete", "prelude", "public",
    "recueil", "redaction", "scenographie", "texte", "theme", "thriller", "tome", "traduction",
    "typographie", "vers", "volume", "ouvrage", "fiction", "recit", "contenu", "structure",
    "imaginaire", "dispositif", "parole", "edition", "signature", "createur"
)
# Partie 5
$words1 += @(
    "abeille", "agneau", "aigle", "albatros", "alligator", "alpaga", "anaconda", "anguille",
    "antilope", "araignee", "autruche", "baleine", "bison", "bouquetin", "buffle", "butor",
    "cachalot", "calamar", "camelle", "canard", "capybara", "caribou", "castor", "caiman",
    "cerf", "chimpanze", "chouette", "cigogne", "cochon", "colibri", "comorant", "corbeau",
    "crabe", "crocodile", "dauphin", "dindon", "dragon", "ecureuil", "elephant", "etoile_de_mer",
    "faucon", "feline", "fourmi", "furet", "girafe", "gorille", "guepard", "hippopotame", "hirondelle",
    "huitre", "iguane", "lama", "lapin", "leopard", "lievre", "lion", "loutre", "lynx",
    "macaque", "manchot", "mangouste", "meerkat", "moufette", "mouette", "mouton", "mulet",
    "naja", "narval", "nuide", "oie", "ornithorynque", "ours", "panda", "paon", "pardo",
    "pelican", "perdrix", "perroquet", "pingouin", "pieuvre", "pigeon", "poney", "porc",
    "porc-epic", "puma", "rhinoceros", "rossignol", "serpent", "singe", "souris", "tapir",
    "taureau", "tigre", "tortue", "trefle", "triton", "vache", "vallaby", "veau", "ver",
    "zebre", "adouri", "aigrette", "anemone", "antilocapra", "aquilon", "babouin",
    "bachata", "badette", "balbuzard", "baudroie", "belier", "beringie", "bergeron", "blatte",
    "boeuf", "bouc", "brame", "buse", "cabiai", "cacatoes", "caille", "cameleon",
    "capitaine", "carpe", "carranche", "casque", "catta", "chacal", "chevre",
    "chevrette", "chevrotin", "choucas", "coati", "cobaye", "coelacanthe", "colombe", "congre",
    "courtiliere", "criquet", "dromadaire", "dugong", "ecrevisse", "eider", "elan", "embryon",
    "equide", "espadon", "esturgeon", "etourneau", "faisan", "fauvette", "flamant", "fulmar",
    "gazelle", "genette", "gecko", "gerbille", "gibbon", "giraffe", "goeland", "gorfou",
    "grison", "guepier", "guanaco", "guerette", "gueule", "haddock", "halicore", "hamster",
    "hermine", "hippocampe", "huppe", "huppinette", "ibis", "indri", "irbis", "jaguar",
    "jaseur", "javanais", "kaiser", "kaki", "kangal", "kinkajou", "kraken", "lagopede",
    "lamantin", "langouste", "laridae", "lemurien", "lemure", "lieutenant", "limpkin", "loriot",
    "lorique", "loup", "luisant", "lutra", "macareux", "maffre", "magellan", "mangabey",
    "manicou", "marmotte", "marsouin", "martin", "mesange", "mitaine", "mollusque", "mouche",
    "mouflon", "mulot", "mure", "mustang", "naia", "nandinie", "nectarinie",
    "nette", "nyala", "ocelot", "ophiure", "orang-outan", "orycterope", "ouette", "outarde",
    "ouvalle", "paresseux", "pavot", "pavus", "pecari", "peluche", "pennatule", "petrel",
    "phacochere", "phalene", "phalanger", "phoque", "pic", "pipistrelle", "piton", "pluvier",
    "pochette", "poirier", "pollux", "pygargue", "quetzal", "ratel", "razorbill", "reptile",
    "requin", "rouget", "rouleau", "salamandre", "salicorne", "sanglier", "sapajou", "sarigue",
    "sauterelle", "scarabee", "serval", "soie", "sparide", "sphinx", "stentor",
    "strepsire", "sturnide", "tamarin", "tamanoir", "tatou", "tetard", "toucan", "traquet",
    "tulipe", "turquet", "urside", "urso", "wapiti", "wasabi", "weasel", "whippet", "xenarthra",
    "xenops", "xerus", "yaqui", "yatagan", "yeti", "youdz", "yrenne", "zebu", "zostere"
)
# Partie 6
$words1 += @(
    "ecole", "college", "universite", "bibliotheque", "enseignant", "professeur", "etudiant", "classe", 
    "bureau", "tableau", "cahier", "stylo", "livre", "examen", "devoir", "recreation", "cour", "parc", 
    "ecole_maternelle", "ecole_primaire", "ecole_secondaire", "lycee", "universite_publique", 
    "universite_privee", "etudes", "diplome", "certificat", "academie", "formation", "enseignement", 
    "pedagogie", "programme", "horaire", "cours", "salle_de_classe", "enseignement_a_distance", 
    "enseignement_en_presentiel", "faculte", "campus", "residence_universitaire", "restaurant_universitaire", 
    "amphitheatre", "laboratoire", "recherche", "dissertation", "memoire", "these", "conference", 
    "seminaire", "atelier", "etude_de_cas", "travaux_pratiques", "travaux_diriges", "repetition", 
    "evaluation", "note", "correction", "bulletin", "rentree_scolaire", "vacances_scolaires", "fete_de_l_ecole", 
    "sortie_scolaire", "voyage_educatif", "echange_etudiant", "bourse_d_etude", "orientation", 
    "counseling", "tutorat", "formation_professionnelle", "emploi_du_temps", "planning", "ressources_pedagogiques", 
    "matieres", "disciplines", "interdisciplinarite", "pedagogie_active", "projet_educatif", "partenariat_educatif", 
    "atelier_creatif", "club_sportif", "ecole_numérique", "enseignement_inclusif", "diversite", "equite", 
    "inclusion", "respect", "collaboration", "participation", "implication", "motivation", "reussite"
)
# Partie 7
$words1 += @(
    "automobile", "voiture", "moteur", "carburant", "essence", "diesel", "electrique", "hybride",
    "roue", "pneu", "jante", "frein", "embrayage", "volant", "siege", "tableau_de_bord", "vitre",
    "coffre", "capot", "portiere", "retro", "phare", "clignotant", "pare_brise", "essuie_glace",
    "echappement", "reservoir", "caisse", "pare_choc", "klaxon", "plaque", "boite_de_vitesse",
    "automatique", "manuelle", "acceleration", "vitesse", "kilometre", "route", "autoroute",
    "rue", "trajet", "gps", "navigation", "radar", "garage", "atelier", "carrosserie", "peinture",
    "reparation", "entretien", "revision", "diagnostic", "permis", "conducteur", "chauffeur",
    "assurance", "taxe", "immatriculation", "achat", "vente", "occasion", "neuf", "prix",
    "marque", "modele", "cabriolet", "sportive", "berline", "monospace", "utilitaire", "camion",
    "remorque", "voiturette", "vehicule", "routeur", "allumage", "starter", "radio", "audio",
    "bluetooth", "chauffage", "climatisation", "cruise_control", "parking", "stationnement",
    "course", "piste", "circuit", "competition", "tourisme", "auto_ecole", "traction", "propulsion",
    "injection", "suspension", "batterie", "charge", "autonomie", "connecte", "technologie",
    "application", "utilisation", "essai", "ligne", "design", "puissance", "coupe", "conception",
    "malus", "bonus", "regulateur", "distance", "chassis", "toit", "bougie", "mode", "eco",
    "sport", "panne", "assistance", "depannage", "courroie", "courant", "energie", "ventilation",
    "siege_arriere", "siege_avant", "essuie_main", "reservoir", "huile", "filtre", "antenne",
    "ampoule", "visibilite", "detailing", "pliage", "vitesse_max", "turbo", "boite_auto",
    "temps", "route_montagne", "carte_grise", "bouton", "starter_motor", "roulage", "feux_stop"
)